"""Public pipeline API for the ScamDNA hackathon crawler."""

from .groq import (
    CLASSIFICATION_CONTRACT,
    DEFAULT_GROQ_MODEL,
    DEFAULT_PROMPT_VERSION,
    GroqClassificationError,
    GroqClient,
    GroqError,
    GroqResult,
)
from .analytics import (
    STRONG_CLUSTER_INDICATOR_TYPES,
    analyze_documents,
    build_analytics,
    build_metrics,
    cluster_documents,
    detect_anomalies,
)
from .openai_analysis import (
    DEFAULT_OPENAI_MODEL,
    DEFAULT_PROMPT_VERSION as DEFAULT_OPENAI_PROMPT_VERSION,
    OpenAIAnalysisClient,
    OpenAIAnalysisError,
    OpenAIAnalysisResult,
    OpenAIInsightResult,
    OpenAIResponseError,
)
from .normalization import (
    VALID_CATEGORIES,
    VALID_INDICATOR_TYPES,
    canonical_url_hash,
    canonicalize_url,
    dedupe_indicators,
    infer_platform,
    normalize_classification,
    normalize_domain,
    normalize_indicator,
    normalize_indicator_type,
    normalize_indicator_value,
    stable_hash,
)
from .query_planner import (
    DEFAULT_DOMAINS,
    DEFAULT_SCAM_INTENTS,
    DateWindow,
    SearchTask,
    build_backfill_tasks,
    build_continuous_tasks,
    continuous_cycle_window,
    monthly_windows,
    split_saturated_task,
    weekly_windows,
)
from .tinyfish import (
    AGENT_MAX_DURATION_SECONDS,
    DEFAULT_AGENT_OUTPUT_SCHEMA,
    TinyFishAgentError,
    TinyFishAgentTimeout,
    TinyFishClient,
    TinyFishError,
    TinyFishFetchError,
    build_agent_goal,
)
from .serpapi import SerpAPIClient, SerpAPIError

__all__ = [
    "AGENT_MAX_DURATION_SECONDS",
    "CLASSIFICATION_CONTRACT",
    "DEFAULT_AGENT_OUTPUT_SCHEMA",
    "DEFAULT_DOMAINS",
    "DEFAULT_GROQ_MODEL",
    "DEFAULT_OPENAI_MODEL",
    "DEFAULT_OPENAI_PROMPT_VERSION",
    "DEFAULT_PROMPT_VERSION",
    "DEFAULT_SCAM_INTENTS",
    "DateWindow",
    "GroqClassificationError",
    "GroqClient",
    "GroqError",
    "GroqResult",
    "OpenAIAnalysisClient",
    "OpenAIAnalysisError",
    "OpenAIAnalysisResult",
    "OpenAIInsightResult",
    "OpenAIResponseError",
    "SearchTask",
    "SerpAPIClient",
    "SerpAPIError",
    "STRONG_CLUSTER_INDICATOR_TYPES",
    "TinyFishAgentError",
    "TinyFishAgentTimeout",
    "TinyFishClient",
    "TinyFishError",
    "TinyFishFetchError",
    "VALID_CATEGORIES",
    "VALID_INDICATOR_TYPES",
    "build_agent_goal",
    "analyze_documents",
    "build_analytics",
    "build_metrics",
    "build_backfill_tasks",
    "build_continuous_tasks",
    "canonical_url_hash",
    "canonicalize_url",
    "continuous_cycle_window",
    "cluster_documents",
    "dedupe_indicators",
    "detect_anomalies",
    "infer_platform",
    "monthly_windows",
    "normalize_classification",
    "normalize_domain",
    "normalize_indicator",
    "normalize_indicator_type",
    "normalize_indicator_value",
    "split_saturated_task",
    "stable_hash",
    "weekly_windows",
]
