export const campaign = {
  id: "CP-2407-19A",
  name: "VNeID SUPPORT LOOP",
  status: "UNDER REVIEW",
  confidence: 87,
  firstSeen: "02 Jul 2026",
  lastSeen: "18 min ago",
  analyst: "Mai Nguyen",
  mentions: 41,
  reports: 12,
  indicators: 8,
  summary:
    "A rotating impersonation campaign moves victims from social posts to Telegram, then to a fake VNeID support APK and mule accounts.",
};

export const bankOptions = ["ALL BANKS", "MB", "VCB", "ACB", "TPBANK", "TECHCOMBANK", "BIDV", "VPBANK"];

export const tacticOptions = [
  "ALL TACTICS",
  "IMPERSONATION",
  "PHISHING",
  "QR RELAY",
  "VISHING",
  "ADVANCE FEE",
  "ACCOUNT TAKEOVER",
  "MALICIOUS APK",
];

export const overviewCampaigns = [
  {
    id: "CP-2407-19A",
    name: "VNeID SUPPORT LOOP",
    plainName: "Fake VNeID support",
    banks: ["MB", "VCB", "ACB"],
    tactics: ["IMPERSONATION", "MALICIOUS APK"],
    status: "RAPIDLY SPREADING",
    severity: "critical",
    confidence: 94,
    reports: 52,
    exposureValue: 214,
    exposure: "₫214M",
    trend: "+18%",
    lastSeen: "18 min ago",
    owner: "Mai Nguyen",
    summary: "Victims are moved from social posts to Telegram, a fake VNeID support APK, and rotating beneficiary accounts.",
    target: "Mobile-banking customers attempting identity verification.",
    recentChange: "A new VCB beneficiary and phone number appeared in three independent reports.",
    nextAction: "Review 2 beneficiary accounts",
    nextActionReason: "The accounts share the same beneficiary cluster; one remains below the automatic block threshold.",
    indicators: ["2 phone numbers", "2 bank accounts", "1 APK", "1 active domain"],
    evidence: ["12 privacy-redacted customer reports", "41 social mentions", "4 canonical evidence records"],
  },
  {
    id: "CP-2407-08C",
    name: "REFUND QR RELAY",
    plainName: "Fake refund QR",
    banks: ["VCB", "TPBANK"],
    tactics: ["QR RELAY", "IMPERSONATION"],
    status: "NEW ACTIVITY",
    severity: "high",
    confidence: 94,
    reports: 29,
    exposureValue: 74,
    exposure: "₫74M",
    trend: "+31%",
    lastSeen: "42 min ago",
    owner: "Linh Tran",
    summary: "Fake support agents promise refunds, then send QR codes that route through intermediary accounts.",
    target: "Customers waiting for ecommerce or card-payment refunds.",
    recentChange: "Two new QR payloads now resolve to the same final beneficiary through different intermediary accounts.",
    nextAction: "Verify the beneficiary cluster",
    nextActionReason: "The final beneficiary match is strong, but one intermediary account has only a single report.",
    indicators: ["4 QR payloads", "3 beneficiary accounts", "2 social handles"],
    evidence: ["9 customer reports", "3 decoded QR records", "2 money-flow matches"],
  },
  {
    id: "CP-2407-21D",
    name: "CREDIT LIMIT UPGRADE",
    plainName: "Fake card-limit upgrade",
    banks: ["ACB", "VPBANK"],
    tactics: ["VISHING", "ADVANCE FEE"],
    status: "NEEDS REVIEW",
    severity: "medium",
    confidence: 83,
    reports: 14,
    exposureValue: 38,
    exposure: "₫38M",
    trend: "+9%",
    lastSeen: "1 hr ago",
    owner: "Quang Pham",
    summary: "Callers impersonate card teams and ask customers to pay a temporary fee to unlock a higher credit limit.",
    target: "Credit-card customers receiving unsolicited upgrade calls.",
    recentChange: "Four reports reuse the same fee script but show two unrelated receiving accounts.",
    nextAction: "Review 4 linked card reports",
    nextActionReason: "Language similarity is high, but the money trail is not yet strong enough to merge the cases.",
    indicators: ["3 caller IDs", "2 accounts", "1 repeated script"],
    evidence: ["4 call transcripts", "6 customer reports", "1 suggested campaign link"],
  },
  {
    id: "CP-2407-17B",
    name: "BIOMETRIC RESET TRAP",
    plainName: "Fake biometric reset",
    banks: ["VCB", "BIDV"],
    tactics: ["PHISHING", "ACCOUNT TAKEOVER"],
    status: "RAPIDLY SPREADING",
    severity: "critical",
    confidence: 92,
    reports: 24,
    exposureValue: 126,
    exposure: "₫126M",
    trend: "+22%",
    lastSeen: "27 min ago",
    owner: "An Le",
    summary: "Fake bank pages claim a biometric reset is required and capture credentials before a device takeover attempt.",
    target: "Customers reacting to new biometric-authentication requirements.",
    recentChange: "The landing page changed domain while keeping the same analytics ID and credential form.",
    nextAction: "Escalate the active domain",
    nextActionReason: "The phishing page is still reachable and has been observed in eight fresh customer sessions.",
    indicators: ["3 domains", "1 analytics ID", "2 device fingerprints"],
    evidence: ["8 browser captures", "11 customer reports", "2 credential-flow recordings"],
  },
  {
    id: "CP-2406-31F",
    name: "REMOTE TASK FARM",
    plainName: "Online task deposit scam",
    banks: ["MB", "TECHCOMBANK"],
    tactics: ["ADVANCE FEE", "IMPERSONATION"],
    status: "MONITORING",
    severity: "low",
    confidence: 89,
    reports: 18,
    exposureValue: 93,
    exposure: "₫93M",
    trend: "-12%",
    lastSeen: "3 hrs ago",
    owner: "Mai Nguyen",
    summary: "Fake online jobs ask victims to deposit increasingly large amounts to unlock tasks and withdrawals.",
    target: "Job seekers contacted through social and messaging platforms.",
    recentChange: "Report volume declined after two receiving accounts were restricted; one domain remains active.",
    nextAction: "Monitor account rotation",
    nextActionReason: "No new beneficiary has crossed the review threshold since the last account restriction.",
    indicators: ["8 domains", "5 accounts", "29 message variants"],
    evidence: ["18 customer reports", "8 redirect captures", "5 money-flow records"],
  },
  {
    id: "CP-2406-12Q",
    name: "MERCHANT REFUND SPOOF",
    plainName: "Merchant refund impersonation",
    banks: ["MB"],
    tactics: ["QR RELAY", "PHISHING"],
    status: "CONTAINED",
    severity: "contained",
    confidence: 97,
    reports: 11,
    exposureValue: 19,
    exposure: "₫19M",
    trend: "-44%",
    lastSeen: "Yesterday",
    owner: "Linh Tran",
    summary: "Impersonated merchants used fake refund forms and QR fees to collect card details and small transfers.",
    target: "Customers disputing purchases with small online merchants.",
    recentChange: "No new infrastructure or beneficiary activity has been observed for 24 hours.",
    nextAction: "Close enhanced monitoring",
    nextActionReason: "Known accounts and domains are actioned, with no fresh activity in the monitoring window.",
    indicators: ["2 domains", "2 QR payloads", "1 account"],
    evidence: ["11 customer reports", "2 merchant impersonation pages", "1 confirmed account"],
  },
];

export const overviewActions = [
  {
    id: "ACT-104",
    campaignId: "CP-2407-19A",
    priority: "URGENT",
    title: "Review 2 VCB beneficiary accounts",
    reason: "Linked to 7 reports; one account is still below the 95% automatic block threshold.",
    owner: "Fraud Operations",
    due: "Due in 2h",
    cta: "OPEN REVIEW",
  },
  {
    id: "ACT-105",
    campaignId: "CP-2407-17B",
    priority: "URGENT",
    title: "Escalate the active biometric-reset domain",
    reason: "The fake login page is still reachable and appeared in 8 fresh customer sessions.",
    owner: "SOC",
    due: "Due in 45m",
    cta: "CREATE SOC CASE",
  },
  {
    id: "ACT-106",
    campaignId: "CP-2407-08C",
    priority: "REVIEW",
    title: "Verify the refund-QR beneficiary cluster",
    reason: "Two new QR payloads route through different accounts to the same final beneficiary.",
    owner: "Fraud Analytics",
    due: "Today",
    cta: "VERIFY CLUSTER",
  },
  {
    id: "ACT-107",
    campaignId: "CP-2407-21D",
    priority: "REVIEW",
    title: "Decide whether to merge 4 card reports",
    reason: "The call script matches, but the receiving accounts are not yet connected.",
    owner: "Card Fraud Team",
    due: "Today",
    cta: "REVIEW REPORTS",
  },
];

export const graphNodes = [
  { id: "campaign", label: "VNeID Support Loop", short: "CP", type: "campaign", group: "campaign", size: 24 },
  { id: "profile", label: "Support Operator 03", short: "P3", type: "profile", group: "campaign", size: 18 },
  { id: "report-12841", label: "Customer report 12,841", short: "R1", type: "report", group: "reports", size: 14 },
  { id: "report-12843", label: "Customer report 12,843", short: "R2", type: "report", group: "reports", size: 14 },
  { id: "telegram-4821", label: "Telegram message 4,821", short: "TG", type: "mention", group: "social", size: 13 },
  { id: "facebook-883", label: "Facebook post 883", short: "FB", type: "mention", group: "social", size: 13 },
  { id: "phone-old", label: "+84 938 441 209", short: "P1", type: "phone", group: "indicators", size: 11 },
  { id: "phone-new", label: "+84 764 882 191", short: "P2", type: "phone", group: "indicators", size: 11 },
  { id: "domain", label: "vneid-ho-tro[.]live", short: "URL", type: "domain", group: "infrastructure", size: 12 },
  { id: "apk", label: "vn.gov.verify.apk", short: "APK", type: "apk", group: "infrastructure", size: 12 },
  { id: "account-old", label: "MB •••• 8086", short: "A1", type: "account", group: "money", size: 12 },
  { id: "account-new", label: "VCB •••• 9214", short: "A2", type: "account", group: "money", size: 12 },
  { id: "phrase", label: "“verify before 11 PM”", short: "TXT", type: "phrase", group: "signals", size: 11 },
  { id: "pixel", label: "Meta Pixel •••8472", short: "PX", type: "tracking", group: "infrastructure", size: 11 },
];

export const graphLinks = [
  { id: "l1", source: "profile", target: "campaign", type: "OPERATES", status: "confirmed", confidence: 96 },
  { id: "l2", source: "telegram-4821", target: "campaign", type: "PART_OF_CAMPAIGN", status: "confirmed", confidence: 94 },
  { id: "l3", source: "facebook-883", target: "campaign", type: "PART_OF_CAMPAIGN", status: "suggested", confidence: 87 },
  { id: "l4", source: "report-12841", target: "campaign", type: "PART_OF_CAMPAIGN", status: "confirmed", confidence: 98 },
  { id: "l5", source: "report-12843", target: "campaign", type: "PART_OF_CAMPAIGN", status: "suggested", confidence: 87 },
  { id: "l6", source: "telegram-4821", target: "phone-old", type: "OBSERVED_IN", status: "confirmed", confidence: 100 },
  { id: "l7", source: "facebook-883", target: "phone-new", type: "OBSERVED_IN", status: "confirmed", confidence: 100 },
  { id: "l8", source: "report-12843", target: "phone-new", type: "OBSERVED_IN", status: "confirmed", confidence: 100 },
  { id: "l9", source: "report-12841", target: "domain", type: "OBSERVED_IN", status: "confirmed", confidence: 100 },
  { id: "l10", source: "domain", target: "apk", type: "REDIRECTS_TO", status: "confirmed", confidence: 99 },
  { id: "l11", source: "domain", target: "pixel", type: "USES", status: "confirmed", confidence: 97 },
  { id: "l12", source: "telegram-4821", target: "phrase", type: "SHARES_TEMPLATE", status: "confirmed", confidence: 94 },
  { id: "l13", source: "facebook-883", target: "phrase", type: "SHARES_TEMPLATE", status: "suggested", confidence: 82 },
  { id: "l14", source: "report-12841", target: "account-old", type: "PAYS_TO", status: "confirmed", confidence: 100 },
  { id: "l15", source: "report-12843", target: "account-new", type: "PAYS_TO", status: "suggested", confidence: 88 },
  { id: "l16", source: "account-old", target: "account-new", type: "SAME_BENEFICIARY_CLUSTER", status: "suggested", confidence: 91 },
  { id: "l17", source: "phone-old", target: "phone-new", type: "ROTATED_TO", status: "suggested", confidence: 87 },
];

export const suggestedRelationship = {
  id: "l5",
  title: "Customer report 12,843 → VNeID Support Loop",
  confidence: 87,
  reason: "Three independent signals bridge this report to the confirmed campaign.",
  evidence: [
    { label: "PHONE ROTATION", value: "+84 764 882 191", note: "first seen 18 min ago" },
    { label: "MONEY FLOW", value: "VCB •••• 9214", note: "same beneficiary cluster" },
    { label: "LANGUAGE", value: "“verify before 11 PM”", note: "82% template similarity" },
  ],
};

export const indicators = [
  { type: "PHONE", value: "+84 938 441 209", state: "SUPERSEDED", sources: 9 },
  { type: "PHONE", value: "+84 764 882 191", state: "NEW", sources: 3 },
  { type: "DOMAIN", value: "vneid-ho-tro[.]live", state: "ACTIONED", sources: 17 },
  { type: "ACCOUNT", value: "MB •••• 8086", state: "MONITORING", sources: 6 },
  { type: "ACCOUNT", value: "VCB •••• 9214", state: "NEW", sources: 2 },
];

export const socialPosts = {
  telegram: {
    platform: "Telegram",
    age: "5h ago",
    title: "Urgent VNeID verification before 11 PM",
    excerpt: "Install the support application and complete verification before your account is locked.",
    reference: "SRC-TG-4821",
  },
  facebook: {
    platform: "Facebook",
    age: "2h ago",
    title: "VNeID support warning uses a new contact number",
    excerpt: "The post repeats the same deadline and routes victims to a Telegram support operator.",
    reference: "SRC-FB-0883",
  },
  customer: {
    platform: "Customer report",
    age: "18m ago",
    title: "Redacted screenshot and transfer destination",
    excerpt: "Reporter received a new phone number, QR code, and the same verification deadline.",
    reference: "RPT-12843",
  },
};

export const evidence = {
  phoneRotation: {
    source: "Customer report 12,843",
    captured: "11 Jul 2026 · 14:42 ICT",
    title: "Phone number rotated",
    excerpt: "+84 764 882 191 replaced the previously confirmed campaign number.",
    reference: "EVD-21F8",
  },
  moneyFlow: {
    source: "Transfer screenshot · redacted",
    captured: "11 Jul 2026 · 14:44 ICT",
    title: "Beneficiary cluster matched",
    excerpt: "VCB •••• 9214 resolves to the same beneficiary cluster as MB •••• 8086.",
    reference: "EVD-87A2",
  },
  language: {
    source: "Cross-platform text match",
    captured: "11 Jul 2026 · 14:45 ICT",
    title: "Verification deadline reused",
    excerpt: "The phrase ‘verify before 11 PM’ matches the confirmed campaign template at 82% similarity.",
    reference: "EVD-9C14",
  },
  infrastructure: {
    source: "Crawler + redirect capture",
    captured: "11 Jul 2026 · 12:18 ICT",
    title: "Infrastructure persisted",
    excerpt: "The new landing domain retains Meta Pixel •••8472 and redirects to vn.gov.verify.apk.",
    reference: "EVD-4D02",
  },
};

function detail({ status, confidence, summary, facts, evidenceItems, posts }) {
  return { status, confidence, summary, facts, evidence: evidenceItems, relatedPosts: posts };
}

export const nodeDetails = {
  campaign: detail({
    status: "CONFIRMED CAMPAIGN",
    confidence: 96,
    summary: "The central campaign record linking social discovery, customer reports, rotated identities, infrastructure, and money flow.",
    facts: [
      { label: "FIRST SEEN", value: "02 Jul 2026", note: "9 days active" },
      { label: "ACTIVE SIGNALS", value: "53 observations", note: "2 source pools" },
      { label: "OWNER", value: "Mai Nguyen", note: "Fraud analyst" },
    ],
    evidenceItems: [evidence.infrastructure, evidence.moneyFlow, evidence.language],
    posts: [socialPosts.telegram, socialPosts.facebook, socialPosts.customer],
  }),
  profile: detail({
    status: "ANALYST PROFILE",
    confidence: 92,
    summary: "Operational persona associated with the VNeID support script. This is an analyst alias, not a verified real-world identity.",
    facts: [
      { label: "KNOWN ALIAS", value: "Support Operator 03", note: "analyst assigned" },
      { label: "CHANNELS", value: "2 Telegram handles", note: "1 retired" },
      { label: "LAST ACTIVE", value: "18 min ago", note: "customer report" },
    ],
    evidenceItems: [evidence.phoneRotation, evidence.language],
    posts: [socialPosts.telegram, socialPosts.customer],
  }),
  "report-12841": detail({
    status: "CONFIRMED REPORT",
    confidence: 98,
    summary: "Privacy-redacted customer report that established the original domain, APK, and MB transfer destination.",
    facts: [
      { label: "RECEIVED", value: "09 Jul · 20:14", note: "official channel" },
      { label: "ARTIFACTS", value: "Screenshot + URL", note: "identity redacted" },
      { label: "LINK STATUS", value: "Confirmed", note: "reviewed by analyst" },
    ],
    evidenceItems: [evidence.infrastructure, evidence.moneyFlow],
    posts: [socialPosts.telegram],
  }),
  "report-12843": detail({
    status: "SUGGESTED LINK",
    confidence: 87,
    summary: "A new privacy-redacted report bridged to the campaign by phone rotation, beneficiary overlap, and language similarity.",
    facts: suggestedRelationship.evidence,
    evidenceItems: [evidence.phoneRotation, evidence.moneyFlow, evidence.language],
    posts: [socialPosts.customer, socialPosts.facebook],
  }),
  "telegram-4821": detail({
    status: "CONFIRMED SOURCE",
    confidence: 94,
    summary: "Crawler-discovered Telegram message containing the confirmed urgency script and original campaign phone number.",
    facts: [
      { label: "PLATFORM", value: "Telegram", note: "public channel" },
      { label: "PUBLISHED", value: "11 Jul · 09:04", note: "5h ago" },
      { label: "CRAWLER ID", value: "4821-TG", note: "stable record" },
    ],
    evidenceItems: [evidence.language, evidence.phoneRotation],
    posts: [socialPosts.telegram, socialPosts.facebook],
  }),
  "facebook-883": detail({
    status: "SUGGESTED SOURCE",
    confidence: 87,
    summary: "A newer Facebook post uses a different phone number but preserves the same deadline and support handoff.",
    facts: [
      { label: "PLATFORM", value: "Facebook", note: "public post" },
      { label: "NEW PHONE", value: "+84 764 882 191", note: "rotated identity" },
      { label: "TEMPLATE", value: "82% similarity", note: "needs review" },
    ],
    evidenceItems: [evidence.phoneRotation, evidence.language],
    posts: [socialPosts.facebook, socialPosts.telegram],
  }),
  "phone-old": detail({
    status: "SUPERSEDED",
    confidence: 100,
    summary: "Original campaign contact number confirmed across nine observations before it stopped appearing.",
    facts: [
      { label: "VALUE", value: "+84 938 441 209", note: "normalized" },
      { label: "SOURCES", value: "9 observations", note: "3 platforms" },
      { label: "LAST SEEN", value: "09 Jul 2026", note: "superseded" },
    ],
    evidenceItems: [evidence.phoneRotation, evidence.language],
    posts: [socialPosts.telegram],
  }),
  "phone-new": detail({
    status: "NEW INDICATOR",
    confidence: 91,
    summary: "Replacement contact number observed in a Facebook post and the latest customer report.",
    facts: [
      { label: "VALUE", value: "+84 764 882 191", note: "normalized" },
      { label: "FIRST SEEN", value: "18 min ago", note: "new rotation" },
      { label: "SOURCES", value: "3 observations", note: "2 independent" },
    ],
    evidenceItems: [evidence.phoneRotation, evidence.language],
    posts: [socialPosts.customer, socialPosts.facebook],
  }),
  domain: detail({
    status: "ACTIONED",
    confidence: 99,
    summary: "Fake VNeID support domain that redirects victims to a malicious Android package.",
    facts: [
      { label: "DOMAIN", value: "vneid-ho-tro[.]live", note: "defanged" },
      { label: "REDIRECT", value: "vn.gov.verify.apk", note: "captured" },
      { label: "ACTION", value: "Takedown submitted", note: "DLV-61C8" },
    ],
    evidenceItems: [evidence.infrastructure, evidence.language],
    posts: [socialPosts.telegram, socialPosts.facebook],
  }),
  apk: detail({
    status: "MALICIOUS APP",
    confidence: 99,
    summary: "Android package delivered by the campaign domain and presented as an official identity-verification update.",
    facts: [
      { label: "PACKAGE", value: "vn.gov.verify.apk", note: "2.8 MB" },
      { label: "SHA-256", value: "81d9…7af2", note: "sandboxed" },
      { label: "PERMISSIONS", value: "SMS + accessibility", note: "high risk" },
    ],
    evidenceItems: [evidence.infrastructure],
    posts: [socialPosts.telegram, socialPosts.customer],
  }),
  "account-old": detail({
    status: "MONITORING",
    confidence: 100,
    summary: "Original recipient account confirmed by six customer reports and connected to the same beneficiary cluster.",
    facts: [
      { label: "ACCOUNT", value: "MB •••• 8086", note: "privacy masked" },
      { label: "REPORTS", value: "6", note: "confirmed" },
      { label: "FLOW", value: "3 intermediary hops", note: "same beneficiary" },
    ],
    evidenceItems: [evidence.moneyFlow],
    posts: [socialPosts.customer],
  }),
  "account-new": detail({
    status: "NEW INDICATOR",
    confidence: 91,
    summary: "New transfer destination connected to the prior mule cluster through beneficiary and timing evidence.",
    facts: [
      { label: "ACCOUNT", value: "VCB •••• 9214", note: "privacy masked" },
      { label: "REPORTS", value: "2", note: "awaiting review" },
      { label: "CLUSTER", value: "Same beneficiary", note: "91% confidence" },
    ],
    evidenceItems: [evidence.moneyFlow, evidence.phoneRotation],
    posts: [socialPosts.customer],
  }),
  phrase: detail({
    status: "LANGUAGE SIGNAL",
    confidence: 82,
    summary: "Urgency phrase reused across Telegram, Facebook, and a customer screenshot despite paraphrasing.",
    facts: [
      { label: "TEMPLATE", value: "verify before 11 PM", note: "normalized" },
      { label: "VARIANTS", value: "7", note: "41 total uses" },
      { label: "SIMILARITY", value: "82%", note: "supporting evidence" },
    ],
    evidenceItems: [evidence.language],
    posts: [socialPosts.telegram, socialPosts.facebook, socialPosts.customer],
  }),
  pixel: detail({
    status: "TRACKING SIGNAL",
    confidence: 97,
    summary: "Tracking identifier reused after the campaign changed domains, providing a durable infrastructure bridge.",
    facts: [
      { label: "TRACKING ID", value: "Meta Pixel •••8472", note: "partially masked" },
      { label: "DOMAINS", value: "8", note: "shared identifier" },
      { label: "FIRST SEEN", value: "02 Jul 2026", note: "persistent" },
    ],
    evidenceItems: [evidence.infrastructure],
    posts: [socialPosts.facebook, socialPosts.telegram],
  }),
};
